/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package familybudget;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Paradise
 */
public class UniversityBudget extends javax.swing.JFrame {

    /**
     * Creates new form UniversityBudget
     */
    public double a,b,c,d,e,f,g,h,i,j,k,l,n,m,o,p,q,r,s,t,u,v,w,x,y,z;
    public double totalincome,totalexpenditure,suplus_deficit;
    
    public UniversityBudget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttutionfees = new javax.swing.JTextField();
        txtsalesofform = new javax.swing.JTextField();
        txtdevelopment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcybercafe = new javax.swing.JTextField();
        txthiringofclassroomhall = new javax.swing.JTextField();
        txtrentfrombuiness = new javax.swing.JTextField();
        txtdonationfromngo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnonstatutoryfee = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcomputertraining = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfixeddepositinterest = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtportalcharge = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtothers = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtexaminationexpenes = new javax.swing.JTextField();
        txtstaffsalary = new javax.swing.JTextField();
        txtlegalexpenses = new javax.swing.JTextField();
        txtsalesoffromscreening = new javax.swing.JTextField();
        txtcasualworker = new javax.swing.JTextField();
        txtcomputerconsumable = new javax.swing.JTextField();
        txtstaffwelfare = new javax.swing.JTextField();
        txtrefundoffee = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtadvertisement = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtmiscellaneous = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtuniversityincome = new javax.swing.JTextField();
        txtuniversityexpenditure = new javax.swing.JTextField();
        txtdeficientsurplus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPUTERIZED BUDGETING SYSTEM  BY STELLA");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "University Income", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tuition/other Fees");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sales of form");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Development levy:");

        txttutionfees.setToolTipText("");
        txttutionfees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttutionfeesKeyTyped(evt);
            }
        });

        txtsalesofform.setToolTipText("");
        txtsalesofform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalesofformActionPerformed(evt);
            }
        });
        txtsalesofform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalesofformKeyTyped(evt);
            }
        });

        txtdevelopment.setToolTipText("");
        txtdevelopment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdevelopmentKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cyber café:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hiring of classroom/hall:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rent from business:");

        txtcybercafe.setToolTipText("");
        txtcybercafe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcybercafeKeyTyped(evt);
            }
        });

        txthiringofclassroomhall.setToolTipText("");
        txthiringofclassroomhall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthiringofclassroomhallKeyTyped(evt);
            }
        });

        txtrentfrombuiness.setToolTipText("");
        txtrentfrombuiness.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrentfrombuinessKeyTyped(evt);
            }
        });

        txtdonationfromngo.setToolTipText("");
        txtdonationfromngo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdonationfromngoKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Donation from Ngo");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Non statutory fee");

        txtnonstatutoryfee.setToolTipText("");
        txtnonstatutoryfee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnonstatutoryfeeKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Computer Training");

        txtcomputertraining.setToolTipText("");
        txtcomputertraining.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomputertrainingKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fixed Deposit Interest");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Portal Charge");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Others");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttutionfees)
                    .addComponent(txtsalesofform)
                    .addComponent(txtdevelopment, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcybercafe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdonationfromngo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtrentfrombuiness, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcomputertraining))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txthiringofclassroomhall, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnonstatutoryfee, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfixeddepositinterest)
                    .addComponent(txtportalcharge)
                    .addComponent(txtothers, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcybercafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdonationfromngo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtfixeddepositinterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txthiringofclassroomhall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnonstatutoryfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtportalcharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtrentfrombuiness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcomputertraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttutionfees, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsalesofform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("University Expenditure"));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recurrent  Expenditure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Examination expenses");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sales of form/screening expenses");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Casual worker:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Computer consumable:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Staff welfare:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Refund of school fees:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Staff salary");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Legal expenses");

        txtexaminationexpenes.setToolTipText("");
        txtexaminationexpenes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtexaminationexpenesKeyTyped(evt);
            }
        });

        txtstaffsalary.setToolTipText("");
        txtstaffsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstaffsalaryKeyTyped(evt);
            }
        });

        txtlegalexpenses.setToolTipText("");
        txtlegalexpenses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlegalexpensesKeyTyped(evt);
            }
        });

        txtsalesoffromscreening.setToolTipText("");
        txtsalesoffromscreening.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalesoffromscreeningKeyTyped(evt);
            }
        });

        txtcasualworker.setToolTipText("");
        txtcasualworker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcasualworkerKeyTyped(evt);
            }
        });

        txtcomputerconsumable.setToolTipText("");
        txtcomputerconsumable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomputerconsumableKeyTyped(evt);
            }
        });

        txtstaffwelfare.setToolTipText("");
        txtstaffwelfare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstaffwelfareKeyTyped(evt);
            }
        });

        txtrefundoffee.setToolTipText("");
        txtrefundoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrefundoffeeKeyTyped(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Advertisement");

        txtadvertisement.setToolTipText("");
        txtadvertisement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadvertisementKeyTyped(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Miscellaneous: ");

        txtmiscellaneous.setToolTipText("");
        txtmiscellaneous.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmiscellaneousKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtexaminationexpenes, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtstaffsalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtlegalexpenses, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsalesoffromscreening, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcasualworker, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcomputerconsumable, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstaffwelfare, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrefundoffee)
                    .addComponent(txtadvertisement)
                    .addComponent(txtmiscellaneous))
                .addGap(107, 107, 107))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtexaminationexpenes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtstaffsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtlegalexpenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtsalesoffromscreening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtcasualworker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtcomputerconsumable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstaffwelfare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtrefundoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtadvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtmiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "University Budget Analysis Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel23.setText("Total University Income:");

        jLabel24.setText("Total University Expenditure:");

        jLabel25.setText("Deficient/Surplus:");

        txtuniversityincome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuniversityincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniversityincomeActionPerformed(evt);
            }
        });

        txtuniversityexpenditure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdeficientsurplus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Plot Bar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Calculate Budget");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Plot Chart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtuniversityincome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuniversityexpenditure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdeficientsurplus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuniversityincome))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuniversityexpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txtdeficientsurplus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/familybudget/img.png"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel26.setText("Save To Database");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttutionfeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttutionfeesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txttutionfeesKeyTyped

    private void txtsalesofformKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalesofformKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtsalesofformKeyTyped

    private void txtdevelopmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevelopmentKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtdevelopmentKeyTyped

    private void txtcybercafeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcybercafeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcybercafeKeyTyped

    private void txthiringofclassroomhallKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthiringofclassroomhallKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txthiringofclassroomhallKeyTyped

    private void txtrentfrombuinessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrentfrombuinessKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrentfrombuinessKeyTyped

    private void txtdonationfromngoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdonationfromngoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdonationfromngoKeyTyped

    private void txtnonstatutoryfeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnonstatutoryfeeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnonstatutoryfeeKeyTyped

    private void txtcomputertrainingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomputertrainingKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomputertrainingKeyTyped

    private void txtexaminationexpenesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtexaminationexpenesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtexaminationexpenesKeyTyped

    private void txtstaffsalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstaffsalaryKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtstaffsalaryKeyTyped

    private void txtlegalexpensesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlegalexpensesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtlegalexpensesKeyTyped

    private void txtsalesoffromscreeningKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalesoffromscreeningKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtsalesoffromscreeningKeyTyped

    private void txtcasualworkerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcasualworkerKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcasualworkerKeyTyped

    private void txtcomputerconsumableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomputerconsumableKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcomputerconsumableKeyTyped

    private void txtstaffwelfareKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstaffwelfareKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtstaffwelfareKeyTyped

    private void txtrefundoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrefundoffeeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrefundoffeeKeyTyped

    private void txtadvertisementKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadvertisementKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadvertisementKeyTyped

    private void txtmiscellaneousKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmiscellaneousKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmiscellaneousKeyTyped

    private void txtuniversityincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniversityincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniversityincomeActionPerformed

    private void txtsalesofformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalesofformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalesofformActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(txttutionfees.getText().equalsIgnoreCase("")){
            a = 0.0;
            txttutionfees.setText(""+a);
        }else{
            a = Double.parseDouble(txttutionfees.getText());
        }
        
        if(txtsalesofform.getText().equalsIgnoreCase("")){
            b = 0.0;
             txtsalesofform.setText(""+b);
        }else{
           b = Double.parseDouble(txtsalesofform.getText());
        }
        
        if(txtdevelopment.getText().equalsIgnoreCase("")){
            c = 0.0;
            txtdevelopment.setText(""+c);
        }else{
            c = Double.parseDouble(txtdevelopment.getText());
        }
        
        if(txtcybercafe.getText().equalsIgnoreCase("")){
            d = 0.0;
            txtcybercafe.setText(""+d);
        }else{
            d = Double.parseDouble(txtcybercafe.getText());
        }
        
        if(txthiringofclassroomhall.getText().equalsIgnoreCase("")){
            e = 0.0;
            txthiringofclassroomhall.setText(""+e);
        }else{
            e = Double.parseDouble(txthiringofclassroomhall.getText());
        }
        
        if(txtrentfrombuiness.getText().equalsIgnoreCase("")){
            f = 0.0;
            txtrentfrombuiness.setText(""+f);
        }else{
            f = Double.parseDouble(txtrentfrombuiness.getText());
        }
        
        if(txtdonationfromngo.getText().equalsIgnoreCase("")){
            g = 0.0;
            txtdonationfromngo.setText(""+g);
        }else{
            g = Double.parseDouble(txtdonationfromngo.getText());
        }
        
        if(txtnonstatutoryfee.getText().equalsIgnoreCase("")){
            h = 0.0;
            txtnonstatutoryfee.setText(""+h);
        }else{
            h = Double.parseDouble(txtnonstatutoryfee.getText());
        }
        if(txtcomputertraining.getText().equalsIgnoreCase("")){
            i = 0.0;
            txtcomputertraining.setText(""+i);
        }else{
            i = Double.parseDouble(txtcomputertraining.getText());
        }
        
        if(txtfixeddepositinterest.getText().equalsIgnoreCase("")){
            j = 0.0;
            txtfixeddepositinterest.setText(""+j);
        }else{
            j = Double.parseDouble(txtfixeddepositinterest.getText());
        }
        
        if(txtportalcharge.getText().equalsIgnoreCase("")){
            k = 0.0;
            txtportalcharge.setText(""+k);
        }else{
            k = Double.parseDouble(txtportalcharge.getText());
        }
        
        if(txtothers.getText().equalsIgnoreCase("")){
            l = 0.0;
            txtothers.setText(""+l);
        }else{
            l = Double.parseDouble(txtportalcharge.getText());
        }
        
        /*          -----  -  --Expenditure-----------------                                                                        */
        
        
        if(txtexaminationexpenes.getText().equalsIgnoreCase("")){
            m = 0.0;
            txtexaminationexpenes.setText(""+m);
        }else{
            m = Double.parseDouble(txtexaminationexpenes.getText());
        }
        
        if(txtstaffsalary.getText().equalsIgnoreCase("")){
            n = 0.0;
            txtstaffsalary.setText(""+n);
        }else{
            n = Double.parseDouble(txtstaffsalary.getText());
        }
        
        if(txtlegalexpenses.getText().equalsIgnoreCase("")){
            o = 0.0;
            txtlegalexpenses.setText(""+o);
        }else{
            o = Double.parseDouble(txtlegalexpenses.getText());
        }
        if(txtsalesoffromscreening.getText().equalsIgnoreCase("")){
            p = 0.0;
            txtsalesoffromscreening.setText(""+p);
        }else{
            p = Double.parseDouble(txtsalesoffromscreening.getText());
        }
        if(txtcasualworker.getText().equalsIgnoreCase("")){
            q = 0.0;
             txtcasualworker.setText(""+q);
        }
        else{
           q = Double.parseDouble(txtcasualworker.getText());
        }
        
        if(txtcomputerconsumable.getText().equalsIgnoreCase("")){
            r = 0.0;
            txtcomputerconsumable.setText(""+r);
        }else{
            
            r = Double.parseDouble(txtcomputerconsumable.getText());
        }
        if(txtstaffwelfare.getText().equalsIgnoreCase("")){
           s = 0.0;
           txtstaffwelfare.setText(""+s);
        }else{
            s = Double.parseDouble(txtstaffwelfare.getText());
        }
        
        if(txtrefundoffee.getText().equalsIgnoreCase("")){
            t = 0.0;
            txtrefundoffee.setText(""+t);
        }else{
            t = Double.parseDouble(txtrefundoffee.getText());
        }
        
        if(txtadvertisement.getText().equalsIgnoreCase("")){
            u = 0.0;
             txtadvertisement.setText(""+u);
        }else{
           u = Double.parseDouble(txtadvertisement.getText());
        }
        if(txtmiscellaneous.getText().equalsIgnoreCase("")){
            v = 0.0;
            txtmiscellaneous.setText(""+v);
        }else{
            v = Double.parseDouble(txtmiscellaneous.getText());
        }
        
        
        /***************Calculation************************/
        
        totalincome = a + b + c + d + e + f + g + h + i + j + k + l;
        txtuniversityincome.setText(String.valueOf(totalincome));
        
        totalexpenditure = m + n + o + p + q + r + s + t + u + v;
        txtuniversityexpenditure.setText(String.valueOf(totalexpenditure));
        
        suplus_deficit = totalincome - totalexpenditure;
        
        txtdeficientsurplus.setText(String.valueOf(suplus_deficit));
        
        if(txtuniversityincome.getText().equalsIgnoreCase("0.0") && txtuniversityexpenditure.getText().equalsIgnoreCase("0.0") && txtdeficientsurplus.getText().equalsIgnoreCase("0.0")){
         JOptionPane.showMessageDialog(null, "Why? Does it mean that you don't have any expenses or income?","Computerized University budget anaysis",JOptionPane.ERROR_MESSAGE);
         }
         else if(totalincome < totalexpenditure){
             JOptionPane.showMessageDialog(null,"Caution!! The university expenditures exceeds is income. \nIt means this budget needs to be amended before sends for approval  ","Computerized budget anaysis",JOptionPane.WARNING_MESSAGE);
         }else {
             JOptionPane.showMessageDialog(null, "Budget seems to be Good.","Computerized university budget anaysis",JOptionPane.INFORMATION_MESSAGE);
         }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         DefaultPieDataset de = new DefaultPieDataset();
        de.setValue("Total Income", Double.parseDouble(txtuniversityincome.getText()));
        de.setValue("Total Budget", Double.parseDouble(txtuniversityexpenditure.getText()));
        de.setValue("Surplus", Double.parseDouble(txtdeficientsurplus.getText()));
        
        JFreeChart chart = ChartFactory.createPieChart("Computerized University Buudget Analysis ", de, true, true, true);
        PiePlot pe = (PiePlot) chart.getPlot();
        ChartFrame frm = new ChartFrame("Computerized University Budget Analysis: ", chart);
        pe.setBackgroundPaint(Color.ORANGE);
        frm.setSize(600,350);
        frm.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
        
         DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(Double.parseDouble(txtuniversityincome.getText()), "Total Income", txtuniversityincome.getText());
        dataset.setValue(Double.parseDouble(txtuniversityexpenditure.getText()),"Total expenses",txtuniversityexpenditure.getText());
        dataset.setValue(Double.parseDouble(txtdeficientsurplus.getText()),"Surplus/Deficit",txtdeficientsurplus.getText());
        
        JFreeChart  chart = ChartFactory.createBarChart3D("Computerised University Budget Analysis","Budget", "Analysis", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot ppp = chart.getCategoryPlot();
        ppp.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame = new ChartFrame("Computerised University  Budget Analysis", chart);
        frame.setSize(700, 550);
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
         
    /*  String tutionfees = txttutionfees.getText();
       String salesform = txtsalesofform.getText();
       String development = txtdevelopment.getText();
       String cybercafe = txtcybercafe.getText();
       String hiringclassroom = txthiringofclassroomhall.getText();
       String rentfrombusiness= txtrentfrombuiness.getText();
       String donationfromngo = txtdonationfromngo.getText();
       String nonstatutoryfee=txtnonstatutoryfee.getText();
       String comptraining = txtcomputertraining.getText();
       String fixeddepositinterest = txtfixeddepositinterest.getText();
       String portalchange = txtportalcharge.getText();
       String others = txtothers.getText();
       String examexpenses = txtexaminationexpenes.getText();
       String staffsalary = txtstaffsalary.getText();
       String legalexpenses = txtlegalexpenses.getText();
       String casualworker = txtcasualworker.getText();
       String compconsumable = txtcomputerconsumable.getText();
       String staffwelfare = txtstaffwelfare.getText();
       String refundofschfee = txtrefundoffee.getText();
       String advertisement = txtadvertisement.getText();
       String miscellenous = txtmiscellaneous.getText();
       String totluniversityincome = txtuniversityincome.getText();
       String totluniversityexpenditure = txtuniversityexpenditure.getText();
       String deficient = txtdeficientsurplus.getText();
      /*if(txttutionfees.equals("")|| txtsalesofform.equals("") || password1.equals("") || password2.equals("") || email.equals("")){
          // error.setText("**ALL FIELDS MUST BE FILLED**");
       }else
           if(!password1.equals(password2)){
               error.setText("**PASSWORD MUST BE THE SAME**");
           }else
           if(!username.equals("") && !password1.equals("") && !password2.equals("") && !email.equals("")){
       */
               try{
                   Class.forName("com.mysql.jdbc.Driver");
                   Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/budget","root","");
                   PreparedStatement ps = con.prepareStatement("INSERT INTO expenditure(tuition_fee,sales_form,development,cybercafe,hiring_of_classroom,rent_from_business,"
                           + "donation_from_ngo,non_statutory_fee,comp_training,fixed_deosit_interest,postal_charge,other,"
                           + "exam_expenses,staff_salary,legal_expenses,screening_expenses,casual_worker,comp_consumable,"
                           + "staff_welfare,refund_of_sch_fee,advertisement,miscellenous,total_university_income,"
                           + "total_university_expenditure,deficient) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                  // ps.setInt(1, Double.parseDouble(a.getText()));
                   ps.setDouble(1, a);
                   ps.setDouble(2, b);
                   ps.setDouble(3, c);
                   ps.setDouble(4, d);
                   ps.setDouble(5, e);
                   ps.setDouble(6, f);
                   ps.setDouble(7, g);
                   ps.setDouble(8, h);
                   ps.setDouble(9, i);
                   ps.setDouble(10, j);
                   ps.setDouble(11, k);
                   ps.setDouble(12, l);
                   
                   
                   ps.setDouble(13, m);
                   ps.setDouble(14, n);
                   ps.setDouble(15, o);
                   ps.setDouble(16, p);
                   ps.setDouble(17, q);
                   ps.setDouble(18, r);
                   ps.setDouble(19, s);
                   ps.setDouble(20, t);
                   ps.setDouble(21, u);
                   ps.setDouble(22, v);
                   ps.setDouble(23, Double.parseDouble(txtuniversityincome.getText()));
                   ps.setDouble(24, Double.parseDouble(txtuniversityexpenditure.getText()));
                   ps.setDouble(25, Double.parseDouble(txtdeficientsurplus.getText()));
                   
              //    ResultSet rs = upd;
                          int upd;
                          upd = ps.executeUpdate();
                          if(upd == 1){
                             // error.setForeground(Color.BLUE);
                             // error.setBackground(Color.WHITE);
                              //JOptionPane.showMessageDialog(null, email);
                           JOptionPane.showMessageDialog(null,"YOU HAVE SUCCESSFULLY REGISTERED");
                          }
                  /*rs = ps.executeQuery();
                  while(rs.next()){
                     ema = rs.getString("email");
                  }
                      if(email.equals(ema)){
                          JOptionPane.showMessageDialog(null,"::Email already exists::","",JOptionPane.ERROR_MESSAGE);
                      }else{
                          ps = con.prepareStatement("INSERT INTO users(fullname,username,password,email) VALUES (?,?,?,?)");
                          ps.setString(1, fullname);
                          ps.setString(2, username);
                          ps.setString(3, password1);
                          ps.setString(4, email);
                          int upd;
                          upd = ps.executeUpdate();
                          if(upd == 1){
                              error.setForeground(Color.BLUE);
                              error.setBackground(Color.WHITE);
                              JOptionPane.showMessageDialog(null, email);
                           error.setText("YOU HAVE SUCCESSFULLY REGISTERED YOU CAN NOW LOGIN BY SIMPLY CLICK ON LOGIN BUTTON");
                          }
                      }*/
               }catch(Exception nn){
               JOptionPane.showMessageDialog(null,nn.getMessage());
               }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversityBudget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtadvertisement;
    private javax.swing.JTextField txtcasualworker;
    private javax.swing.JTextField txtcomputerconsumable;
    private javax.swing.JTextField txtcomputertraining;
    private javax.swing.JTextField txtcybercafe;
    private javax.swing.JTextField txtdeficientsurplus;
    private javax.swing.JTextField txtdevelopment;
    private javax.swing.JTextField txtdonationfromngo;
    private javax.swing.JTextField txtexaminationexpenes;
    private javax.swing.JTextField txtfixeddepositinterest;
    private javax.swing.JTextField txthiringofclassroomhall;
    private javax.swing.JTextField txtlegalexpenses;
    private javax.swing.JTextField txtmiscellaneous;
    private javax.swing.JTextField txtnonstatutoryfee;
    private javax.swing.JTextField txtothers;
    private javax.swing.JTextField txtportalcharge;
    private javax.swing.JTextField txtrefundoffee;
    private javax.swing.JTextField txtrentfrombuiness;
    private javax.swing.JTextField txtsalesofform;
    private javax.swing.JTextField txtsalesoffromscreening;
    private javax.swing.JTextField txtstaffsalary;
    private javax.swing.JTextField txtstaffwelfare;
    private javax.swing.JTextField txttutionfees;
    private javax.swing.JTextField txtuniversityexpenditure;
    private javax.swing.JTextField txtuniversityincome;
    // End of variables declaration//GEN-END:variables
}
